spring.application.name=desertakal
server.port=8080

spring.profiles.active=local

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

spring.docker.compose.file=../compose.yml
spring.docker.compose.enabled=false

spring.jackson.deserialization.fail-on-unknown-properties=false

spring.mvc.throw-exception-if-no-handler-found=true
